In [1]:
from sklearn.svm import SVC
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')
from sklearn.metrics import accuracy_score


In [2]:
df=pd.read_csv('AAPL_ver2.csv')
df


Date        Open        High         Low       Close   Adj Close  \
0      1980-12-12    0.128348    0.128906    0.128348    0.128348    0.099584   
1      1980-12-15    0.122210    0.122210    0.121652    0.121652    0.094388   
2      1980-12-16    0.113281    0.113281    0.112723    0.112723    0.087461   
3      1980-12-17    0.115513    0.116071    0.115513    0.115513    0.089625   
4      1980-12-18    0.118862    0.119420    0.118862    0.118862    0.092224   
...           ...         ...         ...         ...         ...         ...   
10685  2023-05-02  170.089996  170.350006  167.539993  168.539993  168.307190   
10686  2023-05-03  169.500000  170.919998  167.160004  167.449997  167.218704   
10687  2023-05-04  164.889999  167.039993  164.309998  165.789993  165.560989   
10688  2023-05-05  170.979996  174.300003  170.759995  173.570007  173.330261   
10689  2023-05-08  172.479996  173.850006  172.110001  173.500000  173.260345   

          Volume  
0      469033600  
1      175884800  
2      105728000  
3       86441600  
4       73449600  
...          ...  
10685   48425700  
10686   65136000  
10687   81235400  
10688  113316400  
10689   55962800  

[10690 rows x 7 columns]

In [3]:
#Predictor Variables
df['Open-Close'] = df.Open - df.Close
df['High-Low'] = df.High - df.Low
X= df[['Open-Close', 'High-Low']]
X.head()


Open-Close  High-Low
0    0.000000  0.000558
1    0.000558  0.000558
2    0.000558  0.000558
3    0.000000  0.000558
4    0.000000  0.000558

In [4]:
#target variables
y = np.where(df['Close'].shift(-1) > df['Close'],1,0)
y


array([0, 0, 1, ..., 1, 0, 0])

In [6]:
split_percentage = 0.8
split = int(split_percentage*len(df))
  
# Train data set
X_train = X[:split]
y_train = y[:split]
  
# Test data set
X_test = X[split:]
y_test = y[split:]
model = SVC().fit(X_train, y_train)

print ('The predicted targer for tomorrow',model.predict(X)[0])

print(accuracy_score(y_test, model.predict(X_test)))

The predicted targer for tomorrow 0
0.5210477081384471


In [160]:
df1=pd.read_csv('PLTR_ver2.csv')
df1

Date   Open    High   Low  Close  Adj Close     Volume
0    2020-09-30  10.00  11.410  9.11   9.50       9.50  338584400
1    2020-10-01   9.69  10.100  9.23   9.46       9.46  124297600
2    2020-10-02   9.06   9.280  8.94   9.20       9.20   55018300
3    2020-10-05   9.43   9.490  8.92   9.03       9.03   36316900
4    2020-10-06   9.04  10.180  8.90   9.90       9.90   90864000
..          ...    ...     ...   ...    ...        ...        ...
650  2023-05-02   7.72   7.910  7.43   7.59       7.59   38008000
651  2023-05-03   7.62   7.680  7.45   7.56       7.56   24322400
652  2023-05-04   7.47   7.520  7.28   7.38       7.38   29989300
653  2023-05-05   7.44   7.550  7.32   7.41       7.41   45601300
654  2023-05-08   7.64   7.855  7.59   7.74       7.74  105304000

[655 rows x 7 columns]

In [161]:
df1['Open-Close'] = df1.Open - df1.Close
df1['High-Low'] = df1.High - df1.Low
X1= df1[['Open-Close', 'High-Low']]
X1.head()




Open-Close  High-Low
0        0.50      2.30
1        0.23      0.87
2       -0.14      0.34
3        0.40      0.57
4       -0.86      1.28

In [162]:
#target
y1 = np.where(df1['Close'].shift(-1) > df1['Close'],1,0)
y1

array([0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0,

In [163]:
split_percentage = 0.8
split = int(split_percentage*len(df1))
  
# Train data set
X1_train = X1[:split]
y1_train = y1[:split]
  
# Test data set
X1_test = X1[split:]
y1_test = y1[split:]
model = SVC().fit(X1_train, y1_train)

print ('The predicted targer for tomorrow',model.predict(X1)[0])

print(accuracy_score(y1_test, model.predict(X1_test)))

The predicted targer for tomorrow 1
0.5648854961832062


In [175]:
df2=pd.read_csv('NVDA_ver2.csv')
df2


Date        Open        High         Low       Close   Adj Close  \
0     2013-01-02    3.140000    3.182500    3.127500    3.180000    2.936782   
1     2013-01-03    3.180000    3.217500    3.145000    3.182500    2.939091   
2     2013-01-04    3.187500    3.297500    3.177500    3.287500    3.036060   
3     2013-01-07    3.285000    3.295000    3.170000    3.192500    2.948326   
4     2013-01-08    3.200000    3.210000    3.100000    3.122500    2.883681   
...          ...         ...         ...         ...         ...         ...   
2600  2023-05-02  286.799988  288.359985  280.829987  282.100006  282.100006   
2601  2023-05-03  278.399994  283.670013  274.720001  278.019989  278.019989   
2602  2023-05-04  276.510010  278.589996  272.399994  275.619995  275.619995   
2603  2023-05-05  278.260010  287.549988  277.309998  286.799988  286.799988   
2604  2023-05-08  285.220001  292.200012  283.500000  291.510010  291.510010   

        Volume  
0     47883600  
1     29888800  
2     52496800  
3     61073200  
4     46642400  
...        ...  
2600  40273000  
2601  38338700  
2602  32185000  
2603  36101400  
2604  34497900  

[2605 rows x 7 columns]

In [176]:
df2['Open-Close'] = df2.Open - df2.Close
df2['High-Low'] = df2.High - df2.Low
X2= df2[['Open-Close', 'High-Low']]
X2.head()


Open-Close  High-Low
0     -0.0400    0.0550
1     -0.0025    0.0725
2     -0.1000    0.1200
3      0.0925    0.1250
4      0.0775    0.1100

In [177]:
#target
y2 = np.where(df2['Close'].shift(-1) > df2['Close'],1,0)
y2

array([1, 1, 0, ..., 1, 1, 0])

In [178]:
split_percentage = 0.8
split = int(split_percentage*len(df2))
  
# Train data set
X2_train = X2[:split]
y2_train = y2[:split]
  
# Test data set
X2_test = X2[split:]
y2_test = y2[split:]
model = SVC().fit(X2_train, y2_train)

print ('The predicted targer for tomorrow',model.predict(X2)[0])

print(accuracy_score(y2_test, model.predict(X2_test)))

The predicted targer for tomorrow 1
0.5143953934740882
